name: Publish Package to npmjs
on:
  workflow_dispatch:
    inputs:
      options:
        description: 'Publish options'
        required: true
        default: '--dry-run'
        type: choice
        options:
          - '--dry-run'
          - '--provenance --access public'

jobs:
  log-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "--dry-run: $OPTIONS"
        env:
          OPTIONS: ${{ inputs.options }}

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g npm
      - run: npm ci
      - run: npm publish ${OPTIONS}
        env:
          OPTIONS: ${{ inputs.options }}
          NODE_AUTH_TOKEN: ${{ secrets.VTBOT_NPM_TOKEN }}
