name: Publish Package to npmjs
on:
  workflow_dispatch:
    inputs:
      options:
        description: 'Publish options'
        required: true
        default: '--dry-run'
        type: choice
        options:
          - '--dry-run'
          - '--provenance --access public'
          - '--provenance --access public --tag preview'

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g npm
      - run: npm --version
      - run: npm ci
      - run: npm publish ${OPTIONS}
        env:
          OPTIONS: ${{ inputs.options }}
          NODE_AUTH_TOKEN: ${{ secrets.VTBOT_NPM_TOKEN }}
